FROM ghcr.io/apeworx/silverback:v0.7.15 AS base
USER root
WORKDIR /app
COPY --from=ghcr.io/astral-sh/uv:0.7.9 /uv /usr/local/bin/uv
COPY . /app
RUN uv pip install --system --no-cache --compile . \
  && chown -R harambe:harambe /app
USER harambe
ENTRYPOINT ["silverback"]
CMD ["run", "--network", "gnosis:mainnet:alchemy"]
